import { type StateCreator } from 'zustand'
import type { BmpPixelStroke, BmpPixelStrokeDelta } from '../../../../../shared/provinceEditing'

export type PaintActiveTool = 'eyedrop' | 'brush' | 'select-color'

export interface PendingAutoGenerated {
  guid: string
  color: number
  type: 'province' | 'unregistered'
}

export type BmpSaveStatus = 'idle' | 'saving' | 'error'

export interface BmpEditSlice {
  pendingBmpStrokes: BmpPixelStroke[]
  pendingRevertPixels: BmpPixelStrokeDelta[] | null
  paintProvinceColor: number | null
  brushRadius: number
  paintSelection: Set<number>
  paintActiveTool: PaintActiveTool
  pendingAutoGenerated: PendingAutoGenerated | null
  // Save is explicit: PaintPanel's save button bumps this counter, and
  // MapCanvas (which owns the live pixel buffer) watches it to run the save.
  bmpSaveRequestId: number
  bmpSaveStatus: BmpSaveStatus
  bmpSaveError: string | null
  addBmpStroke: (stroke: BmpPixelStroke) => void
  revertBmpStroke: (strokeId: string) => void
  consumePendingRevert: () => void
  clearBmpStrokes: () => void
  setPaintProvinceColor: (color: number | null) => void
  setBrushRadius: (radius: number) => void
  setPaintActiveTool: (tool: PaintActiveTool) => void
  setPendingAutoGenerated: (info: PendingAutoGenerated | null) => void
  addPaintSelectionColor: (packedColor: number) => void
  removePaintSelectionColor: (packedColor: number) => void
  clearPaintSelection: () => void
  requestBmpSave: () => void
  bmpSaveSucceeded: () => void
  bmpSaveFailed: (message: string) => void
}

export const BMP_EDIT_EMPTY = {
  pendingBmpStrokes: [] as BmpPixelStroke[],
  pendingRevertPixels: null as BmpPixelStrokeDelta[] | null,
  paintProvinceColor: null as number | null,
  brushRadius: 5,
  paintSelection: new Set<number>(),
  paintActiveTool: 'brush' as PaintActiveTool,
  pendingAutoGenerated: null as PendingAutoGenerated | null,
  bmpSaveRequestId: 0,
  bmpSaveStatus: 'idle' as BmpSaveStatus,
  bmpSaveError: null as string | null,
}

export const createBmpEditSlice: StateCreator<BmpEditSlice, [], [], BmpEditSlice> = (set) => ({
  ...BMP_EDIT_EMPTY,

  addBmpStroke: (stroke) => set((state) => ({
    pendingBmpStrokes: [...state.pendingBmpStrokes, stroke]
  })),

  // Only the most recently painted stroke can be reverted. A stroke's
  // recorded "old" colors are only valid immediately after it was painted —
  // if a later stroke has since repainted some of the same pixels, restoring
  // an older stroke's colors would overwrite that later work with stale data.
  // Reverting strictly from the top of the stack keeps every revert correct,
  // and repeating it walks back through strokes one at a time.
  revertBmpStroke: (strokeId) => set((state) => {
    const stroke = state.pendingBmpStrokes.at(-1)
    if (!stroke || stroke.id !== strokeId) return {}
    return {
      pendingBmpStrokes: state.pendingBmpStrokes.slice(0, -1),
      pendingRevertPixels: stroke.pixels,
    }
  }),

  consumePendingRevert: () => set({ pendingRevertPixels: null }),

  clearBmpStrokes: () => set({ pendingBmpStrokes: [] }),

  setPaintProvinceColor: (color) => set({ paintProvinceColor: color }),

  setBrushRadius: (radius) => set({ brushRadius: Math.max(1, Math.min(30, radius)) }),

  setPaintActiveTool: (tool) => set({ paintActiveTool: tool }),

  setPendingAutoGenerated: (info) => set({ pendingAutoGenerated: info }),

  addPaintSelectionColor: (packedColor) => set((state) => {
    const next = new Set(state.paintSelection)
    next.add(packedColor)
    return { paintSelection: next }
  }),

  removePaintSelectionColor: (packedColor) => set((state) => {
    const next = new Set(state.paintSelection)
    next.delete(packedColor)
    return { paintSelection: next }
  }),

  clearPaintSelection: () => set({ paintSelection: new Set() }),

  requestBmpSave: () => set((state) => ({
    bmpSaveRequestId: state.bmpSaveRequestId + 1,
    bmpSaveStatus: 'saving',
    bmpSaveError: null,
  })),

  bmpSaveSucceeded: () => set({ bmpSaveStatus: 'idle', bmpSaveError: null, pendingBmpStrokes: [] }),

  bmpSaveFailed: (message) => set({ bmpSaveStatus: 'error', bmpSaveError: message }),
})
